# .github/workflows/docker-image.yaml
#
# See [1] and [2] for more details
#
# [1]: https://github.com/marketplace/actions/build-and-push-docker-images
# [2]: https://github.com/docker/buildx
name: docker-image
on: [ push, pull_request ]
jobs:
  docker-image:
    strategy:
      fail-fast: false
      matrix:
        implementation:
          - sbcl
          - ecl
          - ccl
        include:
          - implementation: sbcl
            dockerfile: Dockerfile.sbcl
          - implementation: ecl
            dockerfile: Dockerfile.ecl
          - implementation: ccl
            dockerfile: Dockerfile.ccl
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image - ${{ matrix.implementation }}
        uses: docker/build-push-action@v3
        with:
          push: false
          file: ${{ matrix.dockerfile }}
          tags: dnaeon/cl-jingle:${{ matrix.implementation }}-latest
